### ISSUE TITLE
Not working with my Epic Games version of the game

### ISSUE THREAD

**Issue by Chachardus** [Lyall/Overcooked2Fix#1]
I attempt to use your fix with the Epic Games version of "Overcooked 2". I followed your instructions, but i don't find any "config" subdirectory located at \BepinEx, and any configuration file named Overcooked2Fix.cfg.

**Comment by Lyall** [comment]
Turns out the version on Epic is 64-bit, which meant I had to add an extra release version. You can choose the Epic version in the [latest release](https://github.com/Lyall/Overcooked2Fix/releases).

![image](https://user-images.githubusercontent.com/695941/169046311-7202a8b5-d1df-4dd1-876c-c85af69a5f1d.png)

**Comment by Chachardus** [comment]
Thanks for the update. It works now flawlessly with Epic Games version.
